### ISSUE TITLE
memory leak: the TaraXLPoseTracking object is not deleted

### ISSUE THREAD

**Issue by nvidiamfilimonov** [econsystems/taraxl-isaac-package#1]
The TaraXLPoseTracking object allocated at https://github.com/econsystems/taraxl-isaac-package/blob/85e6abb760cfe79b2dae6f5adcf89fe03680a99a/packages/taraxl/TaraxlImu.cpp#L56
is not deleted, thus it's memory is leaked.
I suggest using `std::unique_ptr` smart pointer and `std::make_unique` function to avoid the leak.

**Comment by e-consystemgit** [comment]
Hi @nvidiamfilimonov ,

The mentioned suggestion is done in the latest [commit](https://github.com/econsystems/taraxl-isaac-package/commit/ad4cd2ea340c7140acffcbe718a929e2bf19cb8f). Please consider the changes.

Thank you.

**Comment by nvidiamfilimonov** [comment]
Thank you, I suggest also explicitly deleting the TaraXLPoseTracking object by calling `unique_ptr::reset` in `TaraXLIMU::stop()` 
It's allocated at start and not needed after stop.

**Comment by e-consystemgit** [comment]
Done in the commit [here](https://github.com/econsystems/taraxl-isaac-package/commit/b4e5beaeb704d9b6007b1b24504c00208aed5e3a).

**Comment by nvidiamfilimonov** [comment]
The code can be simplified to `taraxlPoseTracking.reset();`
