### ISSUE TITLE
An unnecessary array declaration

### ISSUE THREAD

**Issue by nvidiamfilimonov** [econsystems/taraxl-isaac-package#2]
The `double Q[4]` array declared at https://github.com/econsystems/taraxl-isaac-package/blob/85e6abb760cfe79b2dae6f5adcf89fe03680a99a/packages/taraxl/TaraxlCamera.cpp#L183
is not used in the code.

**Comment by e-consystemgit** [comment]
Hi @nvidiamfilimonov ,

The mentioned suggestion is done in the latest [commit](https://github.com/econsystems/taraxl-isaac-package/commit/ad4cd2ea340c7140acffcbe718a929e2bf19cb8f). Please consider the changes.

Thank you.
