### ISSUE TITLE
Why source files written by Econ have NV copyright

### ISSUE THREAD

**Issue by nvidiamfilimonov** [econsystems/taraxl-isaac-package#3]
I wonder why source files written by Econ have NV copyright in them.

**Comment by e-consystemgit** [comment]
Hi @nvidiamfilimonov ,

The NV copyright files are removed in the latest [commit](https://github.com/econsystems/taraxl-isaac-package/commit/ad4cd2ea340c7140acffcbe718a929e2bf19cb8f). Please consider the changes.

Thank you.

**Comment by nvidiamfilimonov** [comment]
NVIDIA copyright is still present in a workspace file, but it seems to be fine as it is borrowed from the core Isaac SDK.
