### ISSUE TITLE
Add the '.md' extension to README file

### ISSUE THREAD

**Issue by nvidiamfilimonov** [econsystems/taraxl-isaac-package#5]
I suggest to add the `.md` extension to README file to enable correct rendering of Markdown elements.

**Comment by e-consystemgit** [comment]
Sure @nvidiamfilimonov, Added in the commit [here](https://github.com/econsystems/taraxl-isaac-package/commit/be441e04670ddb2901c3137c730857865a0edba0).

**Comment by nvidiamfilimonov** [comment]
Thanks.
