### ISSUE TITLE
Why scaleFactorY is not divided by 2 for Tara USB camera?

### ISSUE THREAD

**Issue by nvidiamfilimonov** [econsystems/taraxl-isaac-package#6]
I wonder why scaleFactorY is not divided by 2 for Tara USB camera?
`scaleFactorY = (double)downscaledRows / (double)selectedResolution.height;`

https://github.com/econsystems/taraxl-isaac-package/blob/32070462d85f67aa35c1e16f071b2e44e6ad5e55/packages/taraxl/TaraxlCamera.cpp#L391-L395

Please, comment this in code.

**Comment by e-consystemgit** [comment]
sure @nvidiamfilimonov  comment added in the commit [e9d5eea](https://github.com/econsystems/taraxl-isaac-package/commit/fc8998b35618df18915d9a133ca58d74ac89e4c0)
